//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargoEmpleado
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public int idCargo { get; set; }
        public bool activo { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
